import { zipSync } from './zip-store.js';

let unityPackageInitialized = false;

function initUnityPackage() {
  if (unityPackageInitialized) return true;
  const projectApi = globalThis.__SSSProject;
  const exportGrid = document.querySelector('#gifBtn')?.closest('.panel-section')?.querySelector('.export-grid');
  if (!projectApi || !(exportGrid instanceof HTMLElement)) return false;
  unityPackageInitialized = true;

  const encoder = new TextEncoder();

  function safeName(value) {
    return String(value || 'sprite-project').trim().replace(/[^a-z0-9_-]+/gi, '-').replace(/^-+|-+$/g, '') || 'sprite-project';
  }

  function canvasToBlob(canvas) {
    return new Promise((resolve, reject) => {
      canvas.toBlob((blob) => blob ? resolve(blob) : reject(new Error('Could not encode atlas PNG.')), 'image/png');
    });
  }

  function buildAtlas(runtime) {
    const entries = [];
    let cellWidth = 1;
    let cellHeight = 1;

    runtime.animations.forEach(([animationName, animation]) => {
      animation.frames.forEach((frame, index) => {
        entries.push({ animationName, animation, frame, index });
        cellWidth = Math.max(cellWidth, frame.canvas.width);
        cellHeight = Math.max(cellHeight, frame.canvas.height);
      });
    });

    if (!entries.length) throw new Error('The project has no frames.');
    const cols = Math.max(1, Math.ceil(Math.sqrt(entries.length)));
    const rows = Math.ceil(entries.length / cols);
    const width = cellWidth * cols;
    const height = cellHeight * rows;
    if (width > 16384 || height > 16384 || width * height > 64 * 1024 * 1024) {
      throw new Error('Unity atlas is too large for a safe single-texture export. Use Multi-atlas instead.');
    }

    const canvas = document.createElement('canvas');
    canvas.width = width;
    canvas.height = height;
    const ctx = canvas.getContext('2d');
    if (!ctx) throw new Error('Canvas 2D is unavailable.');
    ctx.imageSmoothingEnabled = false;

    const sprites = [];
    const animations = [];
    let flatIndex = 0;

    runtime.animations.forEach(([animationName, animation]) => {
      const animationFrames = [];
      animation.frames.forEach((frame, index) => {
        const col = flatIndex % cols;
        const row = Math.floor(flatIndex / cols);
        const x = col * cellWidth;
        const yTop = row * cellHeight;
        const ox = x + Math.floor((cellWidth - frame.canvas.width) / 2);
        const oy = yTop + cellHeight - frame.canvas.height;
        ctx.drawImage(frame.canvas, ox, oy);

        const spriteName = `${safeName(animationName)}_${String(index + 1).padStart(3, '0')}`;
        sprites.push({
          name: spriteName,
          x,
          y: height - yTop - cellHeight,
          width: cellWidth,
          height: cellHeight,
          pivotX: 0.5,
          pivotY: 0,
          durationMs: Math.round((1000 / Math.max(1, animation.fps || 8)) * Math.max(1, frame.hold || 1))
        });
        animationFrames.push(spriteName);
        flatIndex += 1;
      });
      animations.push({
        name: animationName,
        fps: Math.max(1, animation.fps || 8),
        loop: animation.loop !== false,
        pingPong: Boolean(animation.pingPong),
        frames: animationFrames
      });
    });

    return {
      canvas,
      metadata: {
        version: 1,
        generator: 'Sprite Sheet Studio',
        project: runtime.name,
        texture: `${safeName(runtime.name)}-atlas.png`,
        pixelsPerUnit: 100,
        width,
        height,
        sprites,
        animations
      }
    };
  }

  function importerSource() {
    return `// Generated by Sprite Sheet Studio. Place this file under an Editor folder.\nusing System;\nusing System.IO;\nusing UnityEditor;\nusing UnityEngine;\n\npublic static class SpriteSheetStudioImporter\n{\n    [Serializable] private class SpriteEntry\n    {\n        public string name;\n        public int x;\n        public int y;\n        public int width;\n        public int height;\n        public float pivotX;\n        public float pivotY;\n        public int durationMs;\n    }\n\n    [Serializable] private class Metadata\n    {\n        public string texture;\n        public float pixelsPerUnit = 100f;\n        public SpriteEntry[] sprites;\n    }\n\n    [MenuItem(\"Tools/Sprite Sheet Studio/Import Selected Atlas\")]\n    public static void ImportSelectedAtlas()\n    {\n        var texture = Selection.activeObject as Texture2D;\n        if (texture == null)\n        {\n            EditorUtility.DisplayDialog(\"Sprite Sheet Studio\", \"Select the exported atlas texture in the Project window first.\", \"OK\");\n            return;\n        }\n\n        var texturePath = AssetDatabase.GetAssetPath(texture);\n        var jsonPath = Path.ChangeExtension(texturePath, \"json\");\n        if (!File.Exists(jsonPath))\n        {\n            EditorUtility.DisplayDialog(\"Sprite Sheet Studio\", \"Metadata JSON was not found next to the selected atlas.\", \"OK\");\n            return;\n        }\n\n        var metadata = JsonUtility.FromJson<Metadata>(File.ReadAllText(jsonPath));\n        if (metadata == null || metadata.sprites == null || metadata.sprites.Length == 0)\n        {\n            EditorUtility.DisplayDialog(\"Sprite Sheet Studio\", \"Metadata contains no sprites.\", \"OK\");\n            return;\n        }\n\n        var importer = AssetImporter.GetAtPath(texturePath) as TextureImporter;\n        if (importer == null) return;\n\n        importer.textureType = TextureImporterType.Sprite;\n        importer.spriteImportMode = SpriteImportMode.Multiple;\n        importer.filterMode = FilterMode.Point;\n        importer.textureCompression = TextureImporterCompression.Uncompressed;\n        importer.mipmapEnabled = false;\n        importer.alphaIsTransparency = true;\n        importer.spritePixelsPerUnit = metadata.pixelsPerUnit > 0 ? metadata.pixelsPerUnit : 100f;\n\n#pragma warning disable 0618\n        var sheet = new SpriteMetaData[metadata.sprites.Length];\n        for (var i = 0; i < metadata.sprites.Length; i++)\n        {\n            var source = metadata.sprites[i];\n            sheet[i] = new SpriteMetaData\n            {\n                name = source.name,\n                rect = new Rect(source.x, source.y, source.width, source.height),\n                pivot = new Vector2(source.pivotX, source.pivotY),\n                alignment = (int)SpriteAlignment.Custom\n            };\n        }\n        importer.spritesheet = sheet;\n#pragma warning restore 0618\n\n        importer.SaveAndReimport();\n        Selection.activeObject = AssetDatabase.LoadAssetAtPath<Texture2D>(texturePath);\n        EditorUtility.DisplayDialog(\"Sprite Sheet Studio\", $\"Imported {sheet.Length} sprites.\", \"OK\");\n    }\n}\n`;
  }

  async function exportUnityPackage() {
    const runtime = projectApi.runtime();
    const projectName = safeName(runtime.name);
    const atlas = buildAtlas(runtime);
    const png = await canvasToBlob(atlas.canvas);
    const metadataName = `${projectName}-atlas.json`;
    atlas.metadata.texture = `${projectName}-atlas.png`;

    const files = {
      [`Assets/SpriteSheetStudio/${projectName}-atlas.png`]: new Uint8Array(await png.arrayBuffer()),
      [`Assets/SpriteSheetStudio/${metadataName}`]: encoder.encode(JSON.stringify(atlas.metadata, null, 2)),
      'Assets/SpriteSheetStudio/Editor/SpriteSheetStudioImporter.cs': encoder.encode(importerSource()),
      'Assets/SpriteSheetStudio/README.txt': encoder.encode(
        '1. Copy the Assets folder into your Unity project.\n' +
        '2. Wait for Unity to compile the Editor script.\n' +
        `3. Select ${projectName}-atlas.png in the Project window.\n` +
        '4. Run Tools > Sprite Sheet Studio > Import Selected Atlas.\n' +
        'The importer configures Multiple Sprites, Point filtering, no mipmaps and custom pivots.\n' +
        'Animation clip metadata remains available in the JSON for custom tooling.\n'
      )
    };

    const bytes = zipSync(files);
    const blob = new Blob([bytes], { type: 'application/zip' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = `${projectName}-unity-package.zip`;
    document.body.append(anchor);
    anchor.click();
    anchor.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1500);
  }

  const button = document.createElement('button');
  button.className = 'btn export-btn';
  button.innerHTML = '<span>Unity package</span><small>PNG + JSON + C# importer</small>';
  button.addEventListener('click', () => {
    button.disabled = true;
    exportUnityPackage().catch((error) => {
      console.error(error);
      window.alert(error instanceof Error ? error.message : 'Unity export failed.');
    }).finally(() => { button.disabled = false; });
  });
  exportGrid.append(button);
  return true;
}

if (!initUnityPackage()) {
  const timer = window.setInterval(() => {
    if (!initUnityPackage()) return;
    window.clearInterval(timer);
  }, 100);
  window.setTimeout(() => window.clearInterval(timer), 15000);
}
